###################### log ######################
logging:  level:    root: info
    org:
      springframework:
        beans: debug
        context: debug
        web: debug
    jdbc:
      sqlonly: info
      sqltiming: off  
      resultsettable: info  
      audit: off 
      resultset: off 
      connection: off
###################### database ######################
spring:  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:oracle:thin:@182.237.126.19:1521:XE    #url: jdbc:oracle:thin:@182.237.126.19:1521:XE
    username: F2211JDEVELOPER#TEAM3
    password: F2211JDEVELOPER#TEAM3
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    check-template-location: true
    mode: HTML
    cache: false
###################### server, encoding, default-servlet ######################
server:  port: 80
  servlet:    context-path: /final-project-team3-s-team
    encoding:      charset: UTF-8
      enabled: true
      force: true
    register-default-servlet: true
###################### mybatis ######################
mybatis:  type-aliases-package: com.itwill.steam
  configuration:
    map-underscore-to-camel-case: true